# Generated by Django 3.2.8 on 2021-10-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_body', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contact_sent'],
            },
        ),
    ]
