# Generated by Django 3.2.8 on 2021-10-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_slug', models.SlugField(max_length=200)),
                ('blog_heading', models.CharField(max_length=400)),
                ('blog_main', models.TextField()),
                ('blog_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_created', models.DateTimeField(auto_now_add=True)),
                ('blog_updated', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_created'],
            },
        ),
    ]
