# Generated by Django 3.2.8 on 2021-10-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usercomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
