# Generated by Django 3.2.8 on 2021-10-27 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_delete_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_comment', models.DateTimeField(auto_now_add=True)),
                ('main_comment', models.TextField()),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL)),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='blog.blogpost')),
            ],
        ),
    ]
