# Generated by Django 3.2.8 on 2021-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='author_comment',
            field=models.CharField(max_length=50),
        ),
    ]
